// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgxpzbujwruehbjywgio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneHB6YnVqd3J1ZWhianl3Z2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTg4NzksImV4cCI6MjA1MzM3NDg3OX0.SmR2xw8bO-mB7xVbnA0V0lv8qoFUm9aerp8bGWhmU_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);