// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlmhuorcezgwwrgdinca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsbWh1b3JjZXpnd3dyZ2RpbmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NDA2MDAsImV4cCI6MjA1MDQxNjYwMH0.G4XEYDXt398AJ66MSoADwqdfF_gwcP7yhQRr9maPNPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);